/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'patient' : null } |
  { 'admin' : null } |
  { 'doctor' : null } |
  { 'nurse' : null };
export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'doctorId' : Principal,
  'patientId' : Principal,
  'notes' : string,
  'dateTime' : Time,
}
export type AppointmentStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface Doctor {
  'id' : Principal,
  'name' : string,
  'specialty' : string,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'seen' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export interface Nurse {
  'id' : Principal,
  'name' : string,
  'department' : string,
}
export interface Patient { 'id' : Principal, 'age' : bigint, 'name' : string }
export type Time = bigint;
export interface UserProfile {
  'age' : [] | [bigint],
  'appRole' : AppRole,
  'name' : string,
  'specialty' : [] | [string],
  'department' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDoctor' : ActorMethod<[Doctor], undefined>,
  'addNotification' : ActorMethod<[Principal, string], undefined>,
  'addNurse' : ActorMethod<[Nurse], undefined>,
  'assignAppRole' : ActorMethod<[Principal, AppRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Principal, Time], bigint>,
  'cancelAppointment' : ActorMethod<[bigint], undefined>,
  'getAppointment' : ActorMethod<[bigint], [] | [Appointment]>,
  'getAppointmentStats' : ActorMethod<
    [],
    {
      'scheduled' : bigint,
      'total' : bigint,
      'cancelled' : bigint,
      'completed' : bigint,
    }
  >,
  'getAppointmentsForDoctor' : ActorMethod<[Principal], Array<Appointment>>,
  'getAppointmentsForPatient' : ActorMethod<[Principal], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalPatients' : bigint,
      'totalNurses' : bigint,
      'totalDoctors' : bigint,
      'totalAppointments' : bigint,
    }
  >,
  'getDoctor' : ActorMethod<[Principal], [] | [Doctor]>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'getNotifications' : ActorMethod<[Principal], Array<Notification>>,
  'getNurse' : ActorMethod<[Principal], [] | [Nurse]>,
  'getNurses' : ActorMethod<[], Array<Nurse>>,
  'getPatient' : ActorMethod<[Principal], [] | [Patient]>,
  'getPatients' : ActorMethod<[], Array<Patient>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationSeen' : ActorMethod<[Principal, bigint], undefined>,
  'registerPatient' : ActorMethod<[Patient], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];