/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Doctor = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
});
export const Nurse = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const AppRole = IDL.Variant({
  'patient' : IDL.Null,
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
  'nurse' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AppointmentStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Principal,
  'patientId' : IDL.Principal,
  'notes' : IDL.Text,
  'dateTime' : Time,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'appRole' : AppRole,
  'name' : IDL.Text,
  'specialty' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'seen' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Patient = IDL.Record({
  'id' : IDL.Principal,
  'age' : IDL.Nat,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDoctor' : IDL.Func([Doctor], [], []),
  'addNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'addNurse' : IDL.Func([Nurse], [], []),
  'assignAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([IDL.Principal, Time], [IDL.Nat], []),
  'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
  'getAppointment' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
  'getAppointmentStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'scheduled' : IDL.Nat,
          'total' : IDL.Nat,
          'cancelled' : IDL.Nat,
          'completed' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAppointmentsForDoctor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsForPatient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPatients' : IDL.Nat,
          'totalNurses' : IDL.Nat,
          'totalDoctors' : IDL.Nat,
          'totalAppointments' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDoctor' : IDL.Func([IDL.Principal], [IDL.Opt(Doctor)], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getNurse' : IDL.Func([IDL.Principal], [IDL.Opt(Nurse)], ['query']),
  'getNurses' : IDL.Func([], [IDL.Vec(Nurse)], ['query']),
  'getPatient' : IDL.Func([IDL.Principal], [IDL.Opt(Patient)], ['query']),
  'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationSeen' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'registerPatient' : IDL.Func([Patient], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Nat, AppointmentStatus, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Doctor = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
  });
  const Nurse = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const AppRole = IDL.Variant({
    'patient' : IDL.Null,
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
    'nurse' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AppointmentStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Principal,
    'patientId' : IDL.Principal,
    'notes' : IDL.Text,
    'dateTime' : Time,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'appRole' : AppRole,
    'name' : IDL.Text,
    'specialty' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'seen' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Patient = IDL.Record({
    'id' : IDL.Principal,
    'age' : IDL.Nat,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDoctor' : IDL.Func([Doctor], [], []),
    'addNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'addNurse' : IDL.Func([Nurse], [], []),
    'assignAppRole' : IDL.Func([IDL.Principal, AppRole], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([IDL.Principal, Time], [IDL.Nat], []),
    'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
    'getAppointment' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
    'getAppointmentStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'scheduled' : IDL.Nat,
            'total' : IDL.Nat,
            'cancelled' : IDL.Nat,
            'completed' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAppointmentsForDoctor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsForPatient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPatients' : IDL.Nat,
            'totalNurses' : IDL.Nat,
            'totalDoctors' : IDL.Nat,
            'totalAppointments' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDoctor' : IDL.Func([IDL.Principal], [IDL.Opt(Doctor)], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getNurse' : IDL.Func([IDL.Principal], [IDL.Opt(Nurse)], ['query']),
    'getNurses' : IDL.Func([], [IDL.Vec(Nurse)], ['query']),
    'getPatient' : IDL.Func([IDL.Principal], [IDL.Opt(Patient)], ['query']),
    'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationSeen' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'registerPatient' : IDL.Func([Patient], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Nat, AppointmentStatus, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };